# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate adblock

Name:           rust-adblock
Version:        0.7.16
Release:        %autorelease
Summary:        Native Rust module for Adblock Plus syntax

License:        MPL-2.0
URL:            https://crates.io/crates/adblock
Source:         %{crates_source}

Patch:          adblock-disable-benchmarks.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Native Rust module for Adblock Plus syntax (e.g. EasyList, EasyPrivacy)
filter parsing and matching.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+addr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+addr-devel %{_description}

This package contains library source intended for building other packages which
use the "addr" feature of the "%{crate}" crate.

%files       -n %{name}+addr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+content-blocking-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+content-blocking-devel %{_description}

This package contains library source intended for building other packages which
use the "content-blocking" feature of the "%{crate}" crate.

%files       -n %{name}+content-blocking-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+css-validation-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+css-validation-devel %{_description}

This package contains library source intended for building other packages which
use the "css-validation" feature of the "%{crate}" crate.

%files       -n %{name}+css-validation-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cssparser-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cssparser-devel %{_description}

This package contains library source intended for building other packages which
use the "cssparser" feature of the "%{crate}" crate.

%files       -n %{name}+cssparser-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-info-devel %{_description}

This package contains library source intended for building other packages which
use the "debug-info" feature of the "%{crate}" crate.

%files       -n %{name}+debug-info-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+embedded-domain-resolver-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+embedded-domain-resolver-devel %{_description}

This package contains library source intended for building other packages which
use the "embedded-domain-resolver" feature of the "%{crate}" crate.

%files       -n %{name}+embedded-domain-resolver-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-regex-handling-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-regex-handling-devel %{_description}

This package contains library source intended for building other packages which
use the "full-regex-handling" feature of the "%{crate}" crate.

%files       -n %{name}+full-regex-handling-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lifeguard-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lifeguard-devel %{_description}

This package contains library source intended for building other packages which
use the "lifeguard" feature of the "%{crate}" crate.

%files       -n %{name}+lifeguard-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+metrics-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+metrics-devel %{_description}

This package contains library source intended for building other packages which
use the "metrics" feature of the "%{crate}" crate.

%files       -n %{name}+metrics-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+object-pooling-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+object-pooling-devel %{_description}

This package contains library source intended for building other packages which
use the "object-pooling" feature of the "%{crate}" crate.

%files       -n %{name}+object-pooling-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+resource-assembler-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+resource-assembler-devel %{_description}

This package contains library source intended for building other packages which
use the "resource-assembler" feature of the "%{crate}" crate.

%files       -n %{name}+resource-assembler-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+selectors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+selectors-devel %{_description}

This package contains library source intended for building other packages which
use the "selectors" feature of the "%{crate}" crate.

%files       -n %{name}+selectors-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unsync-regex-caching-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unsync-regex-caching-devel %{_description}

This package contains library source intended for building other packages which
use the "unsync-regex-caching" feature of the "%{crate}" crate.

%files       -n %{name}+unsync-regex-caching-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --lib
%endif

%changelog
%autochangelog
