# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate rmp-serde

Name:           rust-rmp-serde0.15
Version:        0.15.5
Release:        %autorelease
Summary:        Serde bindings for RMP

License:        MIT
URL:            https://crates.io/crates/rmp-serde
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21
BuildRequires:  rust-rmpv

%global _description %{expand:
Serde bindings for RMP.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde128-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde128-devel %{_description}

This package contains library source intended for building other packages which
use the "serde128" feature of the "%{crate}" crate.

%files       -n %{name}+serde128-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
